compiler = g++
std = -std=c++11
flag = -o

all:

	$(compiler) $(std) $(flag) 2 2.cpp
	$(compiler) $(std) $(flag) 3 3.cpp
	$(compiler) $(std) $(flag) 4 4.cpp
	$(compiler) $(std) $(flag) dyncharqueue dyncharqueue.h
	$(compiler) $(std) $(flag) 5 5.cpp
