compiler = g++
std = -std=c++11
flag = -o

all:

	$(compiler) $(std) $(flag) assets assets.h
	$(compiler) $(std) $(flag) monsters monsters.h
	$(compiler) $(std) $(flag) players players.h
	$(compiler) $(std) $(flag) main main.cpp

assets:
	$(compiler) $(std) $(flag) assets assets.h
players:
	$(compiler) $(std) $(flag) players players.h
monsters:
	$(compiler) $(std) $(flag) monsters monsters.h
main:
	$(compiler) $(std) $(flag) main main.cpp
