all:

	g++ -c -std=c++11 card.h -o cardh
	g++ -c -std=c++11 monster.h -o monsterh
	g++ -c -std=c++11 player.h -o playerh
	g++ -c -std=c++11 card.cpp -o card
	g++ -c -std=c++11 cardArray.cpp -o cardArray
	g++ -c -std=c++11 monster.cpp -o monster
	g++ -c -std=c++11 deckArray.cpp -o deckArray
	g++ -c -std=c++11 deck.cpp -o deck
	g++ -c -std=c++11 player.cpp -o player
	g++ -std=c++11 -o final final.cpp
	echo
	echo "run ./final"
